# Generated by Django 3.0.1 on 2019-12-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politilive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
